import React, { useState, useEffect } from "react";
import {
  Upload,
  FileAudio,
  Loader2,
  CheckCircle,
  AlertCircle,
  Activity,
  Type,
  Sparkles,
  Copy,
  Check,
  RotateCcw,
} from "lucide-react";
import { analyzeAudio } from "../services/api";

const LOADING_FACTS = [
  "The human brain can recognize a familiar voice in just 0.05 seconds.",
  "Perfect pitch is remarkably rare, occurring in fewer than 1 in 10,000 people.",
  "Acoustic analysis maps 'formants'—the specific resonant frequencies of your vocal tract.",
  "The Nyquist-Shannon theorem dictates that audio must be sampled at double its highest frequency component to prevent aliasing.",

"Standard CD audio is sampled at 44.1 kHz because it cleanly captures the upper limit of human hearing, roughly 20 kHz.",

"A Fast Fourier Transform (FFT) converts time-domain audio waveforms into digestible frequency spectrum metrics.",

"Bit depth determines dynamic range: 16-bit audio provides 96 dB of range, while 24-bit delivers a massive 144 dB.",

"Dither is a microscopic layer of intentional noise added to digital audio to mask quantization distortion.",

"PCM (Pulse Code Modulation) is the raw, uncompressed representation of analog audio signals in a digital state.",
"Acoustic analysis calculates jitter and shimmer to evaluate micro-variations in vocal frequency and amplitude.",

"Phonetics groups human speech sounds into plosives, fricatives, nasals, and vowels based on how airflow is constricted.",

"The space between your vocal cords is called the glottis, the foundational valve of all human vocal synthesis.",

"Women's vocal cords typically vibrate between 180–220 Hz, while men's average around 100–140 Hz due to biological mass.",

"Fricative sounds like 's' and 'f' are essentially controlled broadband noise generated by structural air turbulence.",
"The human ear can distinguish between two sounds that are only 2 milliseconds apart.",

"Your brain uses ITD (Interaural Time Difference) to track a sound's location by calculating the microsecond delay between it hitting each ear.",

"The McGurk Effect proves that what your eyes see can completely alter the vocal phonemes your brain thinks it hears.",

"The human voice is most sensitive in the 2 kHz to 5 kHz range—exactly where critical consonant clarity resides.",

"Your brain automatically fills in missing lower frequencies of a voice if the harmonics are present—a phenomenon called the Missing Fundamental.",

"Whispering does not vibrate your vocal cords; it relies entirely on turbulent airflow creating acoustic friction.",

"Vocal fatigue isn't just a throat muscle issue; your vocal folds collide up to hundreds of times per second during speech.",

"The 'cocktail party effect' is your brain's advanced neural filtering system isolating a single voice out of a chaotic room.",

"Human hearing follows a logarithmic curve, which is why we use the decibel scale instead of linear units to measure loudness.",

"A sudden silence can trigger the exact same neural alert mechanism in the brain as a sudden loud noise.",

"Nasality occurs when the velum lowers, allowing acoustic energy to resonate inside the nasal cavity instead of just the mouth.",

"A standard vowel sound can be mapped accurately using just its first two formant frequencies on an X-Y plot.",

"Speech recognition models map audio to phonemes, the smallest distinct units of sound in a specified language.",

"Prosody refers to the rhythm, melody, and intonation of speech that conveys emotion beyond literal syntax.",

"Cepstral analysis performs a Fourier Transform on a logarithmic spectrum to separate the vocal source from its filter.",

"Dynamic range compression attenuates loud spikes while boosting quiet elements to normalize structural audio signals.",

"Windowing functions like Hanning or Hamming prevent spectral leakage during finite-length Fourier transformations.",

"A spectrogram maps three dimensions of audio simultaneously: time on X, frequency on Y, and amplitude via color intensity.",

"Latency in digital processing is heavily dictated by buffer block sizes—smaller buffers reduce delay but spike CPU loads.",
  "Digital audio breaks sound into tens of thousands of snapshots per second.",
  "The shape of your vocal cords behaves much like a complex wind instrument.",
  "The first recorded sound was captured in 1857 by Édouard-Léon Scott de Martinville on a device that couldn't even play it back.",

"Cardioid microphones get their name because their directional polar pickup pattern is shaped like a classic heart.",

"Condenser microphones utilize a microscopic capacitor plate system to capture highly sensitive acoustic transients.",

"The dynamic microphone relies on electromagnetic induction, using a moving coil inside a magnetic field to generate signal.",

"MP3 compression relies entirely on perceptual coding, stripping out audio data your brain wouldn't easily notice anyway."
,
"Active noise cancellation works by generating an inverted 'anti-noise' sound wave to cancel out exterior ambient sound.",

"The term 'high fidelity' (Hi-Fi) was coined in the 1930s to describe audio gear capable of minimal signal distortion."
,
"A ribbon microphone utilizes an ultra-thin strip of aluminum suspended in a magnetic field to catch directional velocity."
,
"Bluetooth audio compression codecs dynamically balance bitrates depending on the real-time stability of your connection.",

"The modern VU meter measures volume levels using a specialized integration curve designed to replicate human perceived loudness.",
"Sound travels roughly 4.3 times faster in water than in air because molecules are packed much tighter.",

"The speed of sound in air is completely independent of air pressure, changing only with ambient temperature.",

"Anechoic chambers absorb 99.9% of sound reflections, making them so quiet you can hear your own heartbeat and nervous system.",

"Phase cancellation occurs when two identical sound waves meet 180 degrees out of phase, completely flattening the signal.",

"Diffraction allows low-frequency sound waves to easily bend around physical obstacles like walls and pillars.",

"The Doppler Effect shifts pitch higher as a sound source approaches you, compressing the physical wavelengths in front of it.",

"Resonance happens when a sound wave matches the natural frequency of an object, causing it to vibrate intensely.",

"A pure sine wave contains exactly one frequency component with absolutely no harmonic overtones."
,
"White noise contains equal energy across all linear frequencies, while pink noise drops 3 dB per octave to mimic human hearing perception.",

"Infrasound refers to low-frequency waves below 20 Hz, which humans can often physically feel rather than audibly hear."

];

export default function Dashboard() {
  const [file, setFile] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [copiedField, setCopiedField] = useState(null);
  const [factIndex, setFactIndex] = useState(0);

  // Rotate interesting facts while processing audio arrays
  useEffect(() => {
    let interval;
    if (uploading) {
      interval = setInterval(() => {
        setFactIndex((prev) => (prev + 1) % LOADING_FACTS.length);
      }, 3500);
    } else {
      setFactIndex(0);
    }
    return () => clearInterval(interval);
  }, [uploading]);

  const handleFileChange = (e) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      if (selectedFile.type.startsWith("audio/")) {
        setFile(selectedFile);
        setResult(null);
        setError("");
      } else {
        setError("Please select a valid audio file (e.g., MP3, WAV, M4A).");
        setFile(null);
      }
    }
  };

  const handleUpload = async () => {
    if (!file) return;

    setUploading(true);
    setError("");

    try {
      const data = await analyzeAudio(file);
      setResult(data);
    } catch (err) {
      setError(
        err.message || "Could not connect to the server. Is the backend awake?",
      );
    } finally {
      setUploading(false);
    }
  };

  const resetUploader = () => {
    setFile(null);
    setResult(null);
    setError("");
  };

  const copyToClipboard = (text, fieldId) => {
    if (!text) return;
    navigator.clipboard.writeText(text.toString());
    setCopiedField(fieldId);
    setTimeout(() => setCopiedField(null), 2000);
  };

  return (
    <div className="min-h-screen bg-[#030712] text-slate-100 antialiased font-sans selection:bg-indigo-500/30 selection:text-indigo-200 relative overflow-x-hidden">
      {/* Premium Ambient Background Effects */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_-20%,rgba(99,102,241,0.18),transparent_60%)] pointer-events-none" />
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-7xl h-[1px] bg-gradient-to-r from-transparent via-slate-800 to-transparent" />

      <div className="relative max-w-4xl mx-auto px-6 py-20 md:py-28 space-y-12">
        
        {/* Premium Minimal Header Assembly */}
        <header className="text-center max-w-3xl mx-auto space-y-8 select-none">
          {/* Enhanced Bold Micro-Badge Assembly */}
          <div className="inline-flex items-center gap-4 px-6 py-2.5 rounded-2xl bg-slate-950/60 border border-slate-800/80 text-indigo-400 backdrop-blur-xl shadow-[inset_0_1px_2px_rgba(255,255,255,0.05)]">
            <Sparkles size={40} className="text-indigo-400 animate-pulse shrink-0" />
            <h2 className="font-mono text-6xl sm:text-4xl md:text-4xl tracking-[0.25em] font-light text-slate-400 leading-none">
              𝔈𝔫𝔤𝔦𝔫𝔢 ℭ𝔬𝔯𝔢 <span className="font-black bg-gradient-to-r from-indigo-400 to-violet-400 bg-clip-text text-transparent">#𝔚𝔢𝔑𝔖𝔱𝔲𝔡𝔶</span>
            </h2>
          </div>
          
          {/* Premium High-Contrast Typography Stack */}
          <div className="space-y-6">
            <h1 className="text-6xl sm:text-7xl md:text-8xl font-black tracking-tighter bg-gradient-to-b from-white via-slate-200 to-slate-500/60 bg-clip-text text-transparent leading-[0.95] py-1">
              ǟʊɖɨօ ǟռǟʟʐɛʀ
            </h1>
            <p className="text-slate-400 text-m sm:text-base md:text-lg font-normal leading-relaxed max-w-2xl mx-auto tracking-wide">
              𝚄𝚙𝚕𝚘𝚊𝚍 𝚢𝚘𝚞𝚛 𝚛𝚊𝚠 𝚊𝚞𝚍𝚒𝚘 𝚏𝚒𝚕𝚎𝚜 𝚝𝚘 𝚒𝚗𝚜𝚝𝚊𝚗𝚝𝚕𝚢 𝚍𝚎𝚌𝚘𝚍𝚎 𝚟𝚘𝚌𝚊𝚕 𝚙𝚒𝚝𝚌𝚑, 𝚜𝚝𝚛𝚞𝚌𝚝𝚞𝚛𝚊𝚕 𝚏𝚕𝚘𝚠 𝚌𝚘𝚗𝚏𝚒𝚐𝚞𝚛𝚊𝚝𝚒𝚘𝚗𝚜, 𝚊𝚗𝚍 𝚜𝚢𝚗𝚝𝚊𝚡 𝚊𝚗𝚊𝚕𝚢𝚝𝚒𝚌𝚜.
            </p>
          </div>
        </header>

        {/* Unified Vertical Layout Stack */}
        <main className="space-y-8 w-full">
          
          {/* Input Panel (Upload Control) */}
          <section className="bg-slate-900/40 backdrop-blur-xl p-8 md:p-10 rounded-3xl border border-slate-800 shadow-[0_24px_60px_-15px_rgba(0,0,0,0.5)] space-y-8 transition-all duration-300 hover:border-slate-700/40">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800/60 pb-5">
              <div className="space-y-1.5">
                <h3 className="text-xl font-bold text-white tracking-tight">𝙰𝚞𝚍𝚒𝚘 𝙸𝚗𝚝𝚊𝚔𝚎</h3>
                <p className="text-sm text-slate-400">𝙿𝚛𝚘𝚟𝚒𝚍𝚎 𝚊 𝚑𝚒𝚐𝚑-𝚏𝚒𝚍𝚎𝚕𝚒𝚝𝚢 𝚖𝚎𝚍𝚒𝚊 𝚝𝚊𝚛𝚐𝚎𝚝 𝚏𝚘𝚛 𝚜𝚢𝚜𝚝𝚎𝚖 𝚍𝚒𝚊𝚐𝚗𝚘𝚜𝚝𝚒𝚌𝚜.</p>
              </div>
              {result && (
                <button
                  onClick={resetUploader}
                  className="inline-flex items-center gap-2 self-start sm:self-auto px-4 py-2 text-xs font-semibold text-slate-400 hover:text-white bg-slate-950/80 hover:bg-slate-950 rounded-xl border border-slate-800 hover:border-slate-700 transition-all active:scale-95 shadow-sm font-mono"
                >
                  <RotateCcw size={14} />
                  Clear & Upload New
                </button>
              )}
            </div>

            <div className="relative">
              <input
                type="file"
                accept="audio/*"
                onChange={handleFileChange}
                className="hidden"
                id="audio-upload"
                disabled={uploading}
              />
              <label
                htmlFor="audio-upload"
                className={`group flex flex-col items-center justify-center border-2 border-dashed rounded-2xl p-12 md:p-20 cursor-pointer transition-all duration-500 min-h-[260px]
                  ${uploading ? "border-indigo-500/20 bg-indigo-950/5 cursor-wait" : ""}
                  ${!uploading && file ? "border-indigo-500/40 bg-indigo-950/10 shadow-[inset_0_0_30px_rgba(99,102,241,0.05)]" : ""}
                  ${!uploading && !file ? "border-slate-800 bg-slate-950/40 hover:bg-slate-950/60 hover:border-slate-700" : ""}`}
              >
                {uploading ? (
                  <div className="flex flex-col items-center space-y-6 text-center max-w-lg px-4 animate-in fade-in zoom-in-95 duration-300">
                    <div className="p-5 rounded-2xl bg-indigo-500/10 text-indigo-400 shadow-lg ring-1 ring-indigo-500/20">
                      <Loader2 className="animate-spin text-white" size={36} />
                    </div>
                    <div className="space-y-3">
                      <span className="text-lg font-bold tracking-wide block bg-gradient-to-r from-indigo-200 to-slate-200 bg-clip-text text-transparent font-mono">
                        ᴾʳᵒᶜᵉˢˢⁱⁿᵍ ⱽᵒⁱᶜᵉ ᴬʳʳᵃʸˢ...
                      </span>
                      <p className="text-sm md:text-base text-indigo-300/80 italic font-medium min-h-[48px] flex items-center justify-center transition-all duration-500">
                        "{LOADING_FACTS[factIndex]}"
                      </p>
                    </div>
                  </div>
                ) : (
                  <>
                    <div
                      className={`p-5 rounded-2xl transition-all duration-300 shadow-md ${
                        file
                          ? "bg-indigo-600 text-white shadow-indigo-950/50 scale-105"
                          : "bg-slate-900 text-slate-400 group-hover:text-slate-200 group-hover:scale-105"
                      }`}
                    >
                      {file ? <FileAudio size={36} /> : <Upload size={36} />}
                    </div>

                    <div className="text-center mt-6 space-y-2 max-w-[85%]">
                      <span className="font-bold text-base md:text-lg block text-slate-200 group-hover:text-white transition-colors truncate">
                        {file ? file.name : "𝒮𝑒𝓁𝑒𝒸𝓉 𝑜𝓇 𝒹𝓇𝑜𝓅 𝒶𝓊𝒹𝒾𝑜 𝓉𝓇𝒶𝒸𝓀"}
                      </span>
                      <span className="text-xs md:text-sm text-slate-500 block font-medium tracking-wide">
                        {file ? `${(file.size / (1024 * 1024)).toFixed(2)} MB` : "WAV, MP3, or M4A assets"}
                      </span>
                    </div>
                  </>
                )}
              </label>
            </div>

            {error && (
              <div className="p-4 bg-red-950/20 border border-red-500/20 text-red-400 rounded-xl flex items-start gap-3 text-sm animate-in fade-in duration-200">
                <AlertCircle size={18} className="shrink-0 mt-0.5" />
                <span className="font-medium leading-relaxed">{error}</span>
              </div>
            )}

            {!result && (
              <button
                onClick={handleUpload}
                disabled={!file || uploading}
                className={`w-full py-4 px-6 rounded-xl font-bold tracking-wide text-sm md:text-base flex items-center justify-center gap-2.5 transition-all duration-300
                  ${
                    !file || uploading
                      ? "bg-slate-800/40 text-slate-500 cursor-not-allowed border border-slate-800/50"
                      : "bg-white text-slate-950 hover:bg-slate-200 active:scale-[0.99] shadow-xl shadow-white/5 font-bold"
                  }`}
              >
                {uploading ? "Processing..." : "𝑅𝓊𝓃 𝒞𝑜𝓇𝑒 𝒜𝓃𝒶𝓁𝓎𝓈𝓎𝓈"}
              </button>
            )}
          </section>

          {/* Output Panel (Results Matrix) Below the Upload Panel */}
          {result && (
            <section className="bg-slate-900/40 backdrop-blur-xl p-8 md:p-10 rounded-3xl border border-indigo-500/20 shadow-[0_24px_60px_-15px_rgba(99,102,241,0.08)] space-y-8 animate-in fade-in slide-in-from-top-8 duration-700">
              
              <div className="flex items-center justify-between border-b border-slate-800/80 pb-5">
                <div className="flex items-center gap-3 text-emerald-400">
                  <CheckCircle size={24} />
                  <h3 className="text-xl md:text-2xl font-bold tracking-tight text-white">𝕯𝖎𝖆𝖌𝖓𝖔𝖘𝖙𝖎𝖈𝖘 𝕮𝖔𝖒𝖕𝖑𝖊𝖙𝖊</h3>
                </div>
                <span className="text-xs font-mono tracking-widest text-slate-400 bg-slate-950 px-4 py-1.5 rounded-md border border-slate-800/60">
                  #𝙾𝚄𝚃𝙿𝚄🇹
                </span>
              </div>

              {/* Data Grid Cards */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                
                {/* Acoustic Pitch Card */}
                <div className="p-6 rounded-2xl bg-slate-950/40 border border-slate-800/60 space-y-4 relative group hover:border-slate-700/50 transition-colors">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2.5 text-indigo-400">
                      <Activity size={20} className="shrink-0" />
                      <span className="text-sm font-bold uppercase tracking-wider text-indigo-400/90">𝒜c   𝑜𝓊s    𝓉𝒾c 𝒫i𝓉c𝒽</span>
                    </div>
                    <button
                      onClick={() => copyToClipboard(result.analysis.pitch, "pitch")}
                      className="text-slate-500 hover:text-indigo-400 p-2 rounded-lg bg-slate-900/50 hover:bg-slate-900 border border-slate-800 transition-all duration-200"
                      title="Copy Pitch Data"
                    >
                      {copiedField === "pitch" ? <Check size={16} className="text-emerald-400" /> : <Copy size={16} />}
                    </button>
                  </div>
                  <p className="text-lg font-semibold text-slate-200 leading-relaxed">
                    {result.analysis.pitch}
                  </p>
                </div>

                {/* Grammar Core Card */}
                <div className="p-6 rounded-2xl bg-slate-950/40 border border-slate-800/60 space-y-4 relative group hover:border-slate-700/50 transition-colors">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2.5 text-indigo-400">
                      <Type size={20} className="shrink-0" />
                      <span className="text-sm font-bold uppercase tracking-wider text-indigo-400/90">ɠ૨αɱɱα૨ ૮σ૨ε</span>
                    </div>
                    <button
                      onClick={() => copyToClipboard(result.analysis.grammar_issues_found, "grammar")}
                      className="text-slate-500 hover:text-indigo-400 p-2 rounded-lg bg-slate-900/50 hover:bg-slate-900 border border-slate-800 transition-all duration-200"
                      title="Copy Grammar Data"
                    >
                      {copiedField === "grammar" ? <Check size={16} className="text-emerald-400" /> : <Copy size={16} />}
                    </button>
                  </div>
                  <p className="text-lg font-semibold text-slate-200 leading-relaxed">
                    {result.analysis.grammar_issues_found}
                  </p>
                </div>
              </div>

              {/* Transcription Output */}
              <div className="p-6 md:p-8 rounded-2xl bg-slate-950/40 border border-slate-800/60 space-y-4 relative group hover:border-slate-700/50 transition-colors">
                <div className="flex items-center justify-between">
                  <span className="text-sm font-bold text-indigo-400 uppercase tracking-wider block">ɖɛƈօɖɛɖ ȶʀǟ健全ƈʀɨքȶɨօռ</span>
                  <button
                    onClick={() => copyToClipboard(result.analysis.transcription, "transcription")}
                    className="text-slate-500 hover:text-indigo-400 p-2 rounded-lg bg-slate-900/50 hover:bg-slate-900 border border-slate-800 transition-all duration-200"
                    title="Copy Transcription"
                  >
                    {copiedField === "transcription" ? <Check size={16} className="text-emerald-400" /> : <Copy size={16} />}
                  </button>
                </div>
                <p className="text-slate-200 leading-relaxed font-normal text-lg md:text-xl border-l-4 border-indigo-500/40 pl-5 py-1 bg-slate-950/20 rounded-r-xl">
                  "{result.analysis.transcription}"
                </p>
              </div>

            </section>
          )}
        </main>
      </div>
    </div>
  );
}